### PR TITLE
fix smi weight bug

### LINKED ISSUE #150: Canary SMI strategy generates invalid TrafficSplit resource
When the task is used to do a canary deployment, it makes use of SMI (service mesh interface) for doing the `TrafficSplit` to manage which traffic goes to the stable vs. canary version of the service. As part of that, it [automatically goes to get the SMI custom resource version](https://github.com/Azure/k8s-deploy/blob/33608d18f7cac6ef9e3a4b2831622ab560909e88/src/utilities/kubectl-util.ts#L83) currently deployed so it can generate its manifest.

[The manifest it generates uses XXXXm format weights.](https://github.com/Azure/k8s-deploy/blob/33608d18f7cac6ef9e3a4b2831622ab560909e88/src/utilities/strategy-helpers/smi-canary-deployment-helper.ts#L189) That is, you might get a manifest like this:

```yaml
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: my-service-azure-pipelines-rollout
  namespace: my-ns
spec:
  backends:
  - service: my-service-stable
    weight: 1000m
  - service: my-service-baseline
    weight: 0m
  - service: my-service-canary
    weight: 0m
  service: my-service
```

Unfortunately, while the `XXXXm` format [is noted in the very first version of the `TrafficSplit` spec](https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha1/traffic-split.md), as of [version 2 of the spec](https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha2/traffic-split.md) it was removed. The official "SMI SDK for Go" has a detailed custom resource definition [and it validates the weight as a number](https://github.com/servicemeshinterface/smi-sdk-go/blob/a143f8bc96eccdf5fc8a66d0c1622591104c77e0/crds/split.yaml#L148). Further, the [current SMI adapter for Istio uses that SDK](https://github.com/servicemeshinterface/smi-adapter-istio/blob/540c15f49cd800ef32f49751aa89b4464a321203/pkg/controller/trafficsplit/trafficsplit_controller.go#L8) so it's entirely failing to read and validate `TrafficSplit` resources generated during canary.

**The simplest solution is to stop post-fixing `m` on the weights.** The weights being whole/relative numbers or percentages is compatible with all versions of the spec. A correct `TrafficSplit` should look like this:

```yaml
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: my-service-azure-pipelines-rollout
  namespace: my-ns
spec:
  backends:
  - service: my-service-stable
    weight: 1000
  - service: my-service-baseline
    weight: 0
  - service: my-service-canary
    weight: 0
  service: my-service
```

The SMI Adapter for Istio generates logs like this to reflect that issue:

```text
E0902 14:45:23.035319       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha2.TrafficSplit: v1alpha2.TrafficSplitList.Items: []v1alpha2.TrafficSplit: v1alpha2.TrafficSplit.Spec: v1alpha2.TrafficSplitSpec.Backends: []v1alpha2.TrafficSplitBackend: v1alpha2.TrafficSplitBackend.Weight: readUint64: unexpected character: �, error found in #10 byte of ...|"weight":"1000m"},{"|..., bigger context ...|":[{"service":"accounts-service-stable","weight":"1000m"},{"service":"accounts-service-baseline","we|...
E0902 14:45:24.038301       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha2.TrafficSplit: v1alpha2.TrafficSplitList.Items: []v1alpha2.TrafficSplit: v1alpha2.TrafficSplit.Spec: v1alpha2.TrafficSplitSpec.Backends: []v1alpha2.TrafficSplitBackend: v1alpha2.TrafficSplitBackend.Weight: readUint64: unexpected character: �, error found in #10 byte of ...|"weight":"1000m"},{"|..., bigger context ...|":[{"service":"products-service-stable","weight":"1000m"},{"service":"products-service-baseline","we|...
E0902 14:45:25.042071       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha2.TrafficSplit: v1alpha2.TrafficSplitList.Items: []v1alpha2.TrafficSplit: v1alpha2.TrafficSplit.Spec: v1alpha2.TrafficSplitSpec.Backends: []v1alpha2.TrafficSplitBackend: v1alpha2.TrafficSplitBackend.Weight: readUint64: unexpected character: �, error found in #10 byte of ...|"weight":"1000m"},{"|..., bigger context ...|":[{"service":"accounts-service-stable","weight":"1000m"},{"service":"accounts-service-baseline","we|...
```

I'm guessing this logic came [from the original `KubernetesManifest@V0` Azure DevOps task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/KubernetesManifestV0), which is actually where I discovered it. I've [filed a corresponding issue there](https://github.com/microsoft/azure-pipelines-tasks/issues/15250). We're on AzDO right now but will shortly be moving to GitHub Actions (a few months?) and it'd be cool to see it fixed in both places.

### LINKED ISSUE #155: Canary deployment not working with OSM
I need to configure canary deployment with OSM (SMI compatible) https://github.com/openservicemesh/osm
When I configure this task:
`    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        namespace: 'jjweb'
        strategy: canary
        traffic-split-method: smi
        action: deploy #deploy is the default; we will later use this to promote/reject
        percentage: 20
        baseline-and-canary-replicas: 1`

Getting this error, seems some converting problem:
`error: error validating "/tmp/TrafficSplit_jjwebcore_1635240648649": error validating data: [ValidationError(TrafficSplit.spec.backends[0].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[1].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[2].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number"]; if you choose to ignore these errors, turn validation off with --validate=false
Error: Error: error: error validating "/tmp/TrafficSplit_jjwebcore_1635240648649": error validating data: [ValidationError(TrafficSplit.spec.backends[0].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[1].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[2].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number"]; if you choose to ignore these errors, turn validation off with --validate=false`

### PR DESCRIPTION
**Pull request by OliverMKing**
Closes #155 and closes #150

### CODE REVIEW

**Comment by OliverMKing** [comment]
Will build and create a release for this after it's merged in

**Review by davidgamero — APPROVED** [review]

**Review by bfoley13 — APPROVED** [review]

File: src/utilities/strategy-helpers/smi-canary-deployment-helper.ts [hunk 1]
```diff
@@ -186,33 +186,31 @@ function getTrafficSplitObject(kubectl: Kubectl, name: string, stableWeight: num
...
+                    "weight": "${baselineWeight}"
                 },
                 {
-                    "service": "%s",
-                    "weight": "%sm"
+                    "service": "${canaryDeploymentHelper.getCanaryResourceName(name)}",
+                    "weight": "${canaryWeight}"
                 }
             ],
             "service": "%s"
```
Comment (tillig) [inline src/utilities/strategy-helpers/smi-canary-deployment-helper.ts:211]: Looks like this `%s` is still here but not getting formatted in anymore. I think it needs to be `${name}`.

Comment (OliverMKing) [reply src/utilities/strategy-helpers/smi-canary-deployment-helper.ts:211]: Good catch! Will fix
