### PR TITLE
Fixes multiple namespaces bug

### LINKED ISSUE #163: Cannot apply resources with defined namespaces in manifest
### Repro steps:

- Obtain a manifest with defined namespaces (e.g. cert-manager, ingress-nginx)
  - https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/cloud/deploy.yaml
- Add k8s-deploy step that deploys to kubernetes and commit, do not specify a namespece

### Current behaviour:

- Kubernetes deployment fails

```
Error: the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' 
```

```
Error: the namespace from the provided object "ingress-nginx" does not match the namespace "default". You must pass '--namespace=ingress-nginx'
```

### Expected behaviour:

- k8s-deploy should not pass namespace=default parameter to kubectl if namespace is not defined in github action

The reasoning is, official instructions for ingress-nginx, cert-manager and others do not need a namespace parameter in kubectl, and if namespace=default is passed, the command fails. I have to split the manifests into multiple manifests per each namespace as a workaround.

### PR DESCRIPTION
**Pull request by OliverMKing**
Closes #163 

Lets users deploy resources in multiple namespaces elegantly

### CODE REVIEW

File: src/utilities/manifestStabilityUtils.ts [hunk 1]
```diff
@@ -97,37 +112,47 @@ export async function checkPodStatus(
...
+         resource.namespace
+      )
    }
 }
 
-async function getPodStatus(kubectl: Kubectl, podName: string) {
-   const podResult = await kubectl.getResource('pod', podName)
+async function getPodStatus(kubectl: Kubectl, pod: Resource) {
+   const podResult = await kubectl.getResource(
+      'pod',
```
Comment (davidgamero) [inline src/utilities/manifestStabilityUtils.ts:151]: nit: magic string

File: src/utilities/manifestStabilityUtils.ts [hunk 2]
```diff
@@ -85,8 +100,8 @@ export async function checkPodStatus(
    for (let i = 0; i < iterations; i++) {
       await sleep(sleepTimeout)
 
-      core.debug(`Polling for pod status: ${podName}`)
-      podStatus = await getPodStatus(kubectl, podName)
+      core.debug(`Polling for pod status: ${resource.name}`)
```
Comment (davidgamero) [inline src/utilities/manifestStabilityUtils.ts:103]: if this method is just for pods, then does this name change make it harder to understand the code?

File: src/actions/deploy.ts [hunk 3]
```diff
@@ -56,7 +56,9 @@ export async function deploy(
    for (const ingressResource of ingressResources) {
       await kubectl.getResource(
          KubernetesConstants.DiscoveryAndLoadBalancerResource.INGRESS,
-         ingressResource.name
+         ingressResource.name,
```
Comment (jaiveerk) [inline src/actions/deploy.ts:59]: not sure if this is out of scope for this PR, but wonder if we can standardize K8s objects to have namespace in the same field (ie metadata.namespace)? feel like having all objects look the same would make it easier to work with them

File: src/utilities/kubectlUtils.ts [hunk 4]
```diff
@@ -30,7 +30,12 @@ export async function getLastSuccessfulRunSha(
    annotationKey: string
 ): Promise<string> {
    try {
-      const result = await kubectl.getResource('namespace', namespaceName)
+      const result = await kubectl.getResource(
+         'namespace',
```
Comment (jaiveerk) [inline src/utilities/kubectlUtils.ts:34]: nit: can we make this resource type a constant value

File: src/strategyHelpers/deploymentHelper.ts [hunk 5]
```diff
@@ -218,7 +218,12 @@ async function annotateResources(
    )
    if (annotateNamespace) {
       annotateResults.push(
-         await kubectl.annotate('namespace', namespace, annotationKeyValStr)
+         await kubectl.annotate(
+            'namespace',
```
Comment (jaiveerk) [inline src/strategyHelpers/deploymentHelper.ts:222]: again, not sure how reasonable this is but would love to make this value constant

File: src/types/kubectl.ts [hunk 6]
```diff
@@ -3,11 +3,11 @@ import {createInlineArray} from '../utilities/arrayUtils'
 import * as core from '@actions/core'
 import * as toolCache from '@actions/tool-cache'
 import * as io from '@actions/io'
-import {exec} from 'child_process'
 
 export interface Resource {
    name: string
    type: string
+   namespace?: string
```
Comment (jaiveerk) [inline src/types/kubectl.ts:10]: nit: in addition to maybe moving name and namespace into metadata, can we move Resource to k8sobjects.ts?

File: src/types/kubectl.ts [hunk 7]
```diff
@@ -118,82 +128,90 @@ export class Kubectl {
...
-   protected getExecuteFlags(): string[] {
+   protected getFlags(namespaceOverride?: string): string[] {
       const flags = []
       if (this.ignoreSSLErrors) {
          flags.push('--insecure-skip-tls-verify')
       }
-      if (this.namespace) {
-         flags.push('--namespace', this.namespace)
+
+      const ns = namespaceOverride || this.namespace
```
Comment (jaiveerk) [inline src/types/kubectl.ts:212]: love this, super elegant solution 🔥

File: src/utilities/kubectlUtils.ts [hunk 8]
```diff
@@ -53,12 +58,13 @@ export async function annotateChildPods(
    kubectl: Kubectl,
    resourceType: string,
    resourceName: string,
+   namespace: string | undefined,
```
Comment (jaiveerk) [inline src/utilities/kubectlUtils.ts:61]: is there a reason why this isn't just `namespace?: string`

File: src/utilities/manifestStabilityUtils.ts (hunk 2 above)
Comment (jaiveerk) [reply src/utilities/manifestStabilityUtils.ts:103]: I think we should keep the arg as the resource type but would agree that we could make the param name `pod` or something

**Review by jaiveerk — CHANGES_REQUESTED** [review]
looks good for the most part!

can we also modify/add to our integration tests to ensure that multi-namespaced deployments work as intended?

File: src/actions/deploy.ts (hunk 3 above)
Comment (OliverMKing) [reply src/actions/deploy.ts:59]: There's a difference between the actual k8s object and what our app passes around / parses. Standardizing is good but the Resource type is something our code transforms the actual k8s object into so it will have a different model. The Resource type is for our application and our application doesn't need to know about the concept of metadata vs something else.

If we make Resource type the same as a k8s object then a developer would have to know what's useful for this application vs what's not. That's a lot harder than just using a simple object that's parsed from a more complicated one.

File: src/utilities/kubectlUtils.ts (hunk 8 above)
Comment (OliverMKing) [reply src/utilities/kubectlUtils.ts:61]: optional params need to be after other ones.

File: src/actions/deploy.ts (hunk 3 above)
Comment (jaiveerk) [reply src/actions/deploy.ts:59]: makes sense!

**Review by jaiveerk — APPROVED** [review]

**Review by bfoley13 — APPROVED** [review]

File: src/strategyHelpers/canary/canaryHelper.ts [hunk 9]
```diff
@@ -213,6 +217,7 @@ async function cleanUpCanary(
       for (const inputObject of parsedYaml) {
          const name = inputObject.metadata.name
          const kind = inputObject.kind
+         const ns = inputObject?.metadata?.namespace
```
Comment (Tatsinnit) [inline src/strategyHelpers/canary/canaryHelper.ts:220]: 💡 Thought to share:  with this `optional changing` what happens with the scenario, we supply `undefined` in the end? or we might want to add some error handlers in place?

File: src/strategyHelpers/canary/canaryHelper.ts [hunk 10]
```diff
@@ -222,8 +227,8 @@ async function cleanUpCanary(
             const canaryObjectName = getCanaryResourceName(name)
             const baselineObjectName = getBaselineResourceName(name)
 
-            await deleteObject(kind, canaryObjectName)
-            await deleteObject(kind, baselineObjectName)
+            await deleteObject(kind, canaryObjectName, ns)
```
Comment (Tatsinnit) [inline src/strategyHelpers/canary/canaryHelper.ts:230]: 💡 Nit: various places we use `namespaces, for clarity might be `ns` can be renamed to `namespaces`

File: src/types/kubectl.ts [hunk 11]
```diff
@@ -56,16 +56,24 @@ export class Kubectl {
    public async describe(
       resourceType: string,
       resourceName: string,
-      silent: boolean = false
+      silent: boolean = false,
+      namespace?: string
```
Comment (Tatsinnit) [inline src/types/kubectl.ts:60]: 💡thought to share:  Nullish with `?` but type is passed as `string` not `string | null`

Comment (OliverMKing) [reply src/types/kubectl.ts:60]: I was curious about that too. Do you know what the best practice is?

I opted for just `string` instead of `string | undefined` because that's what they do in the [typescript official docs](https://www.typescriptlang.org/docs/handbook/2/functions.html).

Comment (Tatsinnit) [reply src/types/kubectl.ts:60]: ☕️🥷 indeed! ++ , thinking out loud - For anything unintuitive it’s better to mention type upfront. Totally with you, thinking about the function contract for types.

Given you have thought this far, I will go with whatever decision we choose and we have it archived here anyways.

File: src/strategyHelpers/canary/canaryHelper.ts (hunk 9 above)
Comment (OliverMKing) [reply src/strategyHelpers/canary/canaryHelper.ts]: Added some additional typing to make it more explicit.
