### PR TITLE
Resolved issue with Canary deploy

### LINKED ISSUE #240: Bug: Promote operation for canary strategy doesn't work with v4.2 or later
### What happened?

Hi 👋 . I was testing the deployment scenario with `Canary` strategy, but the `promote` operation seems not working.
It just removes the `-canary` pods and it does not promote the original pods, which is similar behavior as `reject`.

### Observed Behaviors
- In my environment,
  - With `@v1.4` and `@v1.5`, deploy successfully promotes canary.
  - With `@v2.0` through `@v4.1`, deploy fails with different errors.
  - With `@v4.2` or later, deploy does not promote the canary.

### Implementations
I am wondering if #165 has some relationship with this behavior. I was trying to fix it, but I am struggling to overcome the errors due to the lack of knowledge around existing codebase. Do you have any insights? (including workaround, misconfiguration, etc.)

- "deploymentHelper" was removed and replaced with "deploy". But I assume it handles `deploy` rather than `promote`.
  - https://github.com/Azure/k8s-deploy/pull/165/files#diff-909286eed5c74f021abae99f94d8edf4f81acbf7d97ae4f8901e2de8a0d425ebL14
  - https://github.com/Azure/k8s-deploy/pull/165/files#diff-909286eed5c74f021abae99f94d8edf4f81acbf7d97ae4f8901e2de8a0d425ebL55
- I am not confident enough, but the behavior seems like the deploy logic tries to perform `deploy` operation at first (instead of `promote`, deploy `-baseline` and `-canary`, then remove the `-canary` as part of the clean-up). If it is true, it would not promote `-canary`.
  - https://github.com/Azure/k8s-deploy/pull/165/files#diff-909286eed5c74f021abae99f94d8edf4f81acbf7d97ae4f8901e2de8a0d425ebL61

### Additional Notes
- `Blue-Green` strategy is working as expected (`-green` pods will be promoted with the `promote` operation).

### Version

- [X] I am using the latest version

### Runner

ubuntu-latest

### Relevant log output

After deploying with Canary `strategy`, I can see the `-baseline` and `-canary` pods deployed along with original pods. I am expecting `-canary` pods to replace original pods after `promote` operation.

**Commands**

```shell
$ kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
ingress-nginx-controller-54d587fbc6-ssh82    1/1     Running   0          2d1h
nginx-deployment-6dc9c6cd6f-bdh77            1/1     Running   0          6h51m
nginx-deployment-6dc9c6cd6f-fr59m            1/1     Running   0          6h51m
nginx-deployment-6dc9c6cd6f-kkhnr            1/1     Running   0          6h51m
nginx-deployment-6dc9c6cd6f-r7r42            1/1     Running   0          6h51m
nginx-deployment-baseline-78cfdc9fb6-vmxt4   1/1     Running   0          5h30m
nginx-deployment-canary-7c497564bb-lrnrb     1/1     Running   0          5h30m
```

```shell
$ kubectl get deploy
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
ingress-nginx-controller    1/1     1            1           2d1h
nginx-deployment            4/4     4            4           29h
nginx-deployment-baseline   1/1     1            1           5h31m
nginx-deployment-canary     1/1     1            1           5h31m
```

**Log with debug log enabled (Excerpt)**

During the "promote", the job tries `Creating canary and baseline objects` (which results in `unchanged` since they're already "deployed"), then `Deleting canary and baseline workloads` occurs.

```
Deploying input manifests
  ##[debug]Input manifest files: /tmp/Deployment_nginx-deployment_1662783396039,/tmp/Service_nginx_1662783396039,/tmp/Service_nginx-preview_1662783396040,/tmp/Ingress_nginx-ingress_1662783396040
  ::group::Deploying manifests

##[debug]Creating canary and baseline objects. Stable object found: 

deployment.apps/nginx-deployment-canary unchanged
deployment.apps/nginx-deployment-baseline configured
service/nginx unchanged
service/nginx-preview unchanged
ingress.networking.k8s.io/nginx-ingress unchanged
##[debug]Deployed manifest files: /tmp/Deployment_nginx-deployment-canary_1662783396511,/tmp/eployment_nginx-deployment-baseline_1662783396511,/tmp/Service_nginx_1662783396511,/tmp/Service_nginx-preview_1662783396511,/tmp/Ingress_nginx-ingress_1662783396511

Deleting canary and baseline workloads
##[debug]Kubectl run with command: /usr/local/bin/kubectl delete,Deployment,nginx-deployment-canary,--insecure-skip-tls-verify
/usr/local/bin/kubectl delete Deployment nginx-deployment-canary --insecure-skip-tls-verify
deployment.apps "nginx-deployment-canary" deleted
##[debug]Kubectl run with command: /usr/local/bin/kubectl delete,Deployment,nginx-deployment-baseline,--insecure-skip-tls-verify
/usr/local/bin/kubectl delete Deployment nginx-deployment-baseline --insecure-skip-tls-verify
deployment.apps "nginx-deployment-baseline" deleted
::endgroup::
```

**Workflow**

```yaml
name: Deploy (Canary)
on:
  workflow_dispatch:
env:
  RESOURCE_GROUP: xxx
  AKS_CLUSTER_NAME: xxx
  SECRET: xxx
  APP_NAME: xxx
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.xxx }}
        username: ${{ secrets.yyy }}
        password: ${{ secrets.zzz }}
    - run: |
        docker build . -t ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
      working-directory: ./xxx
  deployapp:
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - uses: actions/checkout@v3
      - name: Set cluster context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.aaa }}'
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - uses: azure/k8s-create-secret@v1
        name: Create image pull secret
        with:
          container-registry-url: ${{ secrets.xxx }}
          container-registry-username: ${{ secrets.yyy }}
          container-registry-password: ${{ secrets.zzz }}
          namespace: default
          secret-name: ${{ env.SECRET }}
          arguments: --force true
      - name: Deploy app
        uses: k8s-deploy/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            kubernetes/deploy.yaml
            kubernetes/service.yaml
            kubernetes/preview-service.yaml
            kubernetes/ingress.yml
          images: |
            ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          pull-images: false
          strategy: canary
          traffic-split-method: pod
          action: deploy
          percentage: 25
  approveapp:
    runs-on: ubuntu-latest
    needs: deployapp
    environment: akspromotion
    steps:
      - run: echo asked for approval
  promotereject:
    if: always()
    runs-on: ubuntu-latest
    needs: approveapp
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: actions/checkout@v3
      - name: Set cluster context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.aaa }}'
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - name: Promote App
        uses: azure/k8s-deploy@v4
        if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        with:
          namespace: default
          manifests: |
            kubernetes/deploy.yaml
            kubernetes/service.yaml
            kubernetes/preview-service.yaml
            kubernetes/ingress.yml
          images: |
            ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          pull-images: false
          strategy: canary
          traffic-split-method: pod
          action: promote
          percentage: 25
      - name: Reject App
        uses: azure/k8s-deploy@v4
        if: ${{ env.WORKFLOW_CONCLUSION != 'success' }}
        with:
          namespace: default
          manifests: |
            kubernetes/deploy.yaml
            kubernetes/service.yaml
            kubernetes/preview-service.yaml
            kubernetes/ingress.yml
          images: |
            ${{ secrets.xxx }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          pull-images: false
          strategy: canary
          traffic-split-method: pod
          action: reject
          percentage: 25
```

### PR DESCRIPTION
**Pull request by jaiveerk**
This PR fixes #240 and multiple other bugs in the canary strategy.

### CODE REVIEW

File: src/strategyHelpers/canary/podCanaryHelper.ts [hunk 1]
```diff
@@ -8,9 +8,13 @@ import * as canaryDeploymentHelper from './canaryHelper'
 import {isDeploymentEntity} from '../../types/kubernetesTypes'
 import {getReplicaCount} from '../../utilities/manifestUpdateUtils'
 
-export async function deployPodCanary(filePaths: string[], kubectl: Kubectl) {
+export async function deployPodCanary(
+   filePaths: string[],
+   kubectl: Kubectl,
+   onlyDeployStable: boolean = false
```
Comment (OliverMKing) [inline src/strategyHelpers/canary/podCanaryHelper.ts:14]: In general boolean parameters to functions should just be a separate function.

deployPodCanary
deployPodCanaryStableOnly

more like this but this is an important fix (plus other things can be fixed up so we can just wait on a refactor)

File: src/strategyHelpers/canary/podCanaryHelper.ts [hunk 2]
```diff
@@ -22,45 +26,32 @@ export async function deployPodCanary(filePaths: string[], kubectl: Kubectl) {
...
-            // Get stable object
-            core.debug('Querying stable object')
+            const newCanaryObject = canaryDeploymentHelper.getNewCanaryResource(
+               inputObject,
+               canaryReplicaCount
+            )
+            newObjectsList.push(newCanaryObject)
+
+            // if there's already a stable object, deploy baseline as well
+            // TODO: get rid of baseline objects entirely
```
Comment (OliverMKing) [inline src/strategyHelpers/canary/podCanaryHelper.ts:44]: what do you mean by this TODO?

File: src/strategyHelpers/canary/smiCanaryHelper.ts [hunk 3]
```diff
@@ -6,74 +6,96 @@ import * as yaml from 'js-yaml'
...
-   if (canaryReplicaCount < 0 || canaryReplicaCount > 100)
+export async function deploySMICanary(
+   filePaths: string[],
+   kubectl: Kubectl,
+   onlyDeployStable: boolean = false
+) {
+   const canaryReplicasInput = core.getInput('baseline-and-canary-replicas')
+   let canaryReplicaCount
+   let calculateReplicas = true
+   core.debug(`prior to if, input is ${canaryReplicasInput}`)
```
Comment (OliverMKing) [inline src/strategyHelpers/canary/smiCanaryHelper.ts]: unneeded debug

File: src/strategyHelpers/canary/smiCanaryHelper.ts [hunk 4]
```diff
@@ -6,74 +6,96 @@ import * as yaml from 'js-yaml'
...
+   if (canaryReplicasInput !== '') {
+      core.debug('canary replicas input is ' + canaryReplicasInput)
+      canaryReplicaCount = parseInt(canaryReplicasInput)
+      calculateReplicas = false
+      core.debug(
```
Comment (OliverMKing) [inline src/strategyHelpers/canary/smiCanaryHelper.ts:28]: extra debug

File: src/types/kubectl.ts [hunk 5]
```diff
@@ -170,7 +173,24 @@ export class Kubectl {
          args = args.concat(['--namespace', this.namespace])
       }
       core.debug(`Kubectl run with command: ${this.kubectlPath} ${args}`)
-      return await getExecOutput(this.kubectlPath, args, {silent})
+
+      // TODO: eventually refactor to use something like this/the errorable pattern
+      // let toReturn: ExecOutput
```
Comment (OliverMKing) [inline src/types/kubectl.ts:178]: can remove this todo for now. This basically applies to the entire codebase

**Review by OliverMKing — CHANGES_REQUESTED** [review]

**Comment by OliverMKing** [comment]
Looks solid to me (just a few debug statements to cleanup)! Excited for integration test additions in the future as well.

File: src/strategyHelpers/canary/podCanaryHelper.ts (hunk 1 above)
Comment (jaiveerk) [reply src/strategyHelpers/canary/podCanaryHelper.ts:14]: yeah there's stuff like it scattered all over the codebase, was gonna wait to just do a bulk fix + include testing and do that all at once

File: src/strategyHelpers/canary/podCanaryHelper.ts (hunk 2 above)
Comment (jaiveerk) [reply src/strategyHelpers/canary/podCanaryHelper.ts:44]: this was pre-our discussion yesterday, I originally thought it didn't make sense to group baseline with canary since generally a stable deployment will already exist but I see the value of it, so removing it. Thanks for catching that!

**Review by OliverMKing — APPROVED** [review]

**Review by bfoley13 — APPROVED** [review]
